package com.github.kotlintelegrambot.entities.files

internal object FilesFields {
    const val fileId = "file_id"
    const val fileUniqueId = "file_unique_id"
    const val width = "width"
    const val height = "height"
    const val duration = "duration"
    const val thumb = "thumb"
    const val fileName = "file_name"
    const val mimeType = "mime_type"
    const val fileSize = "file_size"
    const val performer = "performer"
    const val title = "title"
    const val length = "length"
    const val isAnimated = "is_animated"
    const val emoji = "emoji"
    const val setName = "set_name"
    const val maskPosition = "mask_position"
    const val filePath = "file_path"
    const val smallFileId = "small_file_id"
    const val smallFileUniqueId = "small_file_unique_id"
    const val bigFileId = "big_file_id"
    const val bigFileUniqueId = "big_file_unique_id"
}
