package com.github.kotlintelegrambot.entities

import com.github.kotlintelegrambot.entities.dice.Dice
import com.github.kotlintelegrambot.entities.files.Animation
import com.github.kotlintelegrambot.entities.files.Audio
import com.github.kotlintelegrambot.entities.files.Document
import com.github.kotlintelegrambot.entities.files.PhotoSize
import com.github.kotlintelegrambot.entities.files.Video
import com.github.kotlintelegrambot.entities.files.VideoNote
import com.github.kotlintelegrambot.entities.files.Voice
import com.github.kotlintelegrambot.entities.payments.RefundedPayment
import com.github.kotlintelegrambot.entities.payments.SuccessfulPayment
import com.github.kotlintelegrambot.entities.polls.Poll
import com.github.kotlintelegrambot.entities.stickers.Sticker
import com.google.gson.annotations.SerializedName as Name

data class Message(
    @Name("message_id") val messageId: Long,
    val from: User? = null,
    @Name("sender_chat") val senderChat: Chat? = null,
    val date: Long,
    val chat: Chat,
    @Name("forward_from") val forwardFrom: User? = null,
    @Name("forward_from_chat") val forwardFromChat: Chat? = null,
    @Name("forward_from_message_id") val forwardFromMessageId: Int? = null,
    @Name("forward_signature") val forwardSignature: String? = null,
    @Name("forward_sender_name") val forwardSenderName: String? = null,
    @Name("forward_date") val forwardDate: Int? = null,
    @Name("reply_to_message") val replyToMessage: Message? = null,
    @Name("via_bot") val viaBot: User? = null,
    @Name("edit_date") val editDate: Int? = null,
    @Name("media_group_id") val mediaGroupId: String? = null,
    @Name("author_signature") val authorSignature: String? = null,
    val text: String? = null,
    val entities: List<MessageEntity>? = null,
    @Name("caption_entities") val captionEntities: List<MessageEntity>? = null,
    val audio: Audio? = null,
    val document: Document? = null,
    val animation: Animation? = null,
    @Name("dice") val dice: Dice? = null,
    val game: Game? = null,
    val photo: List<PhotoSize>? = null,
    val sticker: Sticker? = null,
    val video: Video? = null,
    val voice: Voice? = null,
    @Name("video_note") val videoNote: VideoNote? = null,
    val caption: String? = null,
    val contact: Contact? = null,
    val location: Location? = null,
    val venue: Venue? = null,
    @Name("new_chat_members") val newChatMembers: List<User>? = null,
    val poll: Poll? = null,
    @Name("left_chat_member") val leftChatMember: User? = null,
    @Name("new_chat_title") val newChatTitle: String? = null,
    @Name("new_chat_photo") val newChatPhoto: List<PhotoSize>? = null,
    @Name("delete_chat_photo") val deleteChatPhoto: Boolean? = null,
    @Name("group_chat_created") val groupChatCreated: Boolean? = null,
    @Name("supergroup_chat_created") val supergroupChatCreated: Boolean? = null,
    @Name("channel_chat_created") val channelChatCreated: Boolean? = null,
    @Name("migrate_to_chat_id") val migrateToChatId: Long? = null,
    @Name("migrate_from_chat_id") val migrateFromChatId: Long? = null,
    val invoice: Invoice? = null,
    @Name("successful_payment") val successfulPayment: SuccessfulPayment? = null,
    @Name("refunded_payment") val refundedPayment: RefundedPayment? = null,
    @Name("reply_markup") val replyMarkup: InlineKeyboardMarkup? = null,
    @Name("proximity_alert_triggered") val proximityAlertTriggered: ProximityAlertTriggered? = null,
    @Name("web_app_data") val webAppData: WebAppData? = null,
    @Name("message_thread_id") val messageThreadId: Long? = null,
    @Name("is_topic_message") val isTopicMessage: Boolean? = null,
    @Name("forward_origin") val forwardOrigin: MessageOrigin? = null,
    @Name("link_preview_options") val linkPreviewOptions: LinkPreviewOptions? = null,
    @Name("forum_topic_created") val forumTopicCreated: ForumTopicCreated? = null,
    @Name("forum_topic_closed") val forumTopicClosed: ForumTopicClosed? = null,
    @Name("forum_topic_reopened") val forumTopicReopened: ForumTopicReopened? = null,
    @Name("forum_topic_edited") val forumTopicEdited: ForumTopicEdited? = null,
    @Name("general_forum_topic_hidden") val generalForumTopicHidden: GeneralForumTopicHidden? = null,
    @Name("general_forum_topic_unhidden") val generalForumTopicUnhidden: GeneralForumTopicUnhidden? = null,
    @Name("write_access_allowed") val writeAccessAllowed: WriteAccessAllowed? = null,
    @Name("users_shared") val usersShared: UsersShared? = null,
    @Name("chat_shared") val chatShared: ChatShared? = null,
    @Name("has_media_spoiler") val hasMediaSpoiler: Boolean? = null,
    @Name("has_protected_content") val hasProtectedContent: Boolean? = null,
    @Name("is_from_offline") val isFromOffline: Boolean? = null,
    @Name("business_connection_id") val businessConnectionId: String? = null,
    @Name("sender_business_bot") val senderBusinessBot: User? = null,
    @Name("effect_id") val effectId: String? = null,
    @Name("show_caption_above_media") val showCaptionAboveMedia: Boolean? = null,
    @Name("paid_media") val paidMedia: com.github.kotlintelegrambot.entities.payments.PaidMediaInfo? = null,
    @Name("external_reply") val externalReply: ExternalReplyInfo? = null,
    @Name("quote") val quote: TextQuote? = null,
    @Name("reply_to_story") val replyToStory: Story? = null,
    @Name("story") val story: Story? = null,
    @Name("boost_added") val boostAdded: ChatBoostAdded? = null,
    @Name("sender_boost_count") val senderBoostCount: Int? = null,
    @Name("chat_background_set") val chatBackgroundSet: ChatBackground? = null,
    @Name("giveaway_created") val giveawayCreated: GiveawayCreated? = null,
    @Name("giveaway") val giveaway: Giveaway? = null,
    @Name("giveaway_winners") val giveawayWinners: GiveawayWinners? = null,
    @Name("giveaway_completed") val giveawayCompleted: GiveawayCompleted? = null,
    @Name("gift") val gift: com.github.kotlintelegrambot.entities.gifts.GiftInfo? = null,
    @Name("unique_gift") val uniqueGift: com.github.kotlintelegrambot.entities.gifts.UniqueGiftInfo? = null,
    @Name("paid_star_count") val paidStarCount: Int? = null,
    @Name("checklist") val checklist: com.github.kotlintelegrambot.entities.checklists.Checklist? = null,
    @Name("checklist_tasks_done") val checklistTasksDone: com.github.kotlintelegrambot.entities.checklists.ChecklistTasksDone? = null,
    @Name("checklist_tasks_added") val checklistTasksAdded: com.github.kotlintelegrambot.entities.checklists.ChecklistTasksAdded? = null,
    @Name("direct_message_price_changed") val directMessagePriceChanged: DirectMessagePriceChanged? = null,
    @Name("paid_message_price_changed") val paidMessagePriceChanged: PaidMessagePriceChanged? = null,
    @Name("suggested_post_approved") val suggestedPostApproved: com.github.kotlintelegrambot.entities.suggestedposts.SuggestedPostApproved? = null,
    @Name("suggested_post_approval_failed") val suggestedPostApprovalFailed: com.github.kotlintelegrambot.entities.suggestedposts.SuggestedPostApprovalFailed? = null,
    @Name("suggested_post_declined") val suggestedPostDeclined: com.github.kotlintelegrambot.entities.suggestedposts.SuggestedPostDeclined? = null,
    @Name("suggested_post_paid") val suggestedPostPaid: com.github.kotlintelegrambot.entities.suggestedposts.SuggestedPostPaid? = null,
    @Name("suggested_post_refunded") val suggestedPostRefunded: com.github.kotlintelegrambot.entities.suggestedposts.SuggestedPostRefunded? = null,
    @Name("suggested_post_info") val suggestedPostInfo: com.github.kotlintelegrambot.entities.suggestedposts.SuggestedPostInfo? = null,
    @Name("is_paid_post") val isPaidPost: Boolean? = null,
    @Name("direct_messages_topic") val directMessagesTopic: com.github.kotlintelegrambot.entities.suggestedposts.DirectMessagesTopic? = null,
    @Name("chat_owner_left") val chatOwnerLeft: ChatOwnerLeft? = null,
    @Name("chat_owner_changed") val chatOwnerChanged: ChatOwnerChanged? = null,
    @Name("sender_tag") val senderTag: String? = null,
    @Name("managed_bot_created") val managedBotCreated: ManagedBotCreated? = null,
    @Name("managed_bot_updated") val managedBotUpdated: ManagedBotUpdated? = null,
    @Name("reply_to_checklist_task_id") val replyToChecklistTaskId: Int? = null,
    @Name("reply_to_poll_option_id") val replyToPollOptionId: String? = null,
    @Name("guest_bot_caller_user") val guestBotCallerUser: User? = null,
    @Name("guest_bot_caller_chat") val guestBotCallerChat: Chat? = null,
    @Name("guest_query_id") val guestQueryId: String? = null,
    @Name("live_photo") val livePhoto: com.github.kotlintelegrambot.entities.files.LivePhoto? = null,
)
